language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - "pip install ."
  - pip install -r devenv-requirements.txt
script:
  - flake8 nredarwin
  - flake8 tests
  - coverage run --source=nredarwin/ setup.py test
  - coverage report
